// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig, env } from 'prisma/config';

export default defineConfig({
    schema: 'libs/providers/src/prisma',
    migrations: {
        path: 'libs/providers/src/prisma/migrations',
    },
    //engine: 'classic',
    datasource: {
        url: env('DATABASE_URL'),
    },
});

// This file is not needed for Prisma configuration
// Prisma configuration is done through:
// 1. prisma/schema.prisma file
// 2. Environment variables (DATABASE_URL in .env)
// 3. package.json scripts
// You can delete this file or use it for custom tooling
