export enum ReservationStatus {
    PENDING = 'PENDING',
    FLIGHT_RESERVED = 'FLIGHT_RESERVED',
    HOTEL_RESERVED = 'HOTEL_RESERVED',
    CAR_RESERVED = 'CAR_RESERVED',
    PAYMENT_PROCESSED = 'PAYMENT_PROCESSED',
    CONFIRMED = 'CONFIRMED',
    FAILED = 'FAILED',
    COMPENSATING = 'COMPENSATING',
    CANCELLED = 'CANCELLED',
}
